name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip + install dev deps (retry)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          for i in 1 2 3; do
            pip install -r requirements-dev.txt && break || sleep 5
          done

      - name: Lint (flake8)
        run: flake8 --config .flake8

      - name: Tests (pytest)
        run: pytest -q

      - name: Smoke test
        run: python -c "print('Smoke test OK')"
