name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # flake8 fest pinnen + bei Netz-Hiccups 3x versuchen
      - name: Upgrade pip + install flake8 (pinned, retry)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          for i in 1 2 3; do
            pip install --index-url https://pypi.org/simple flake8==7.1.1 && break || sleep 5
          done

      - name: Lint (repo root = alerts_v2)
        run: flake8 --config .flake8

      - name: Smoke test
        run: python -c "print(\"Smoke test OK\")"
