name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip + install dev deps (retry)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          for i in 1 2 3; do
            pip install -r requirements-dev.txt && break || sleep 5
          done

      - name: Lint (flake8)
        run: flake8 --config .flake8

      - name: Tests (pytest + coverage)
        run: |
          pytest -q \
            --cov=app --cov=core --cov=exec --cov=ilog --cov=strategy \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml \
            --cov-fail-under=70

      - name: Upload coverage.xml
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Smoke test
        run: python -c "print('Smoke test OK')"
